### ISSUE TITLE
ngx-uploader.com

### ISSUE THREAD

**Issue by jkuri** [bleenco/ngx-uploader#519] opened 2020-07-12 21:01 UTC
Can someone from @bleenco renew certificate for https://ngx-uploader.com please. Otherwise this looks kinda abandoned.

/cc @irmana

**Comment by DavideViolante** [comment] 2020-11-12 21:50
Duplicate of https://github.com/bleenco/ngx-uploader/issues/493

**Comment by irmana** [comment] 2020-11-16 13:23
I apologize for the delay and thanks for reporting. This should be fixed now. /cc @belsakn 

-- Irman

**Closed by irmana** 2020-11-16 13:23 UTC
